# Generated by Django 4.2 on 2022-11-11 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_city_alter_employee_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', to_field='employee_id'),
        ),
    ]
